server:
  port: 11000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: marketing-service
          uri: lb://marketing-service
          predicates:
            - Path=/marketing/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/product/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka